# Generated by Django 4.2.8 on 2023-12-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField()),
                ("location", models.CharField(max_length=510)),
                ("description", models.TextField()),
                ("participants_allowed", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("profile_picture", models.FileField(null=True, upload_to="")),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.event",
                    ),
                ),
            ],
        ),
    ]
